#
# Copyright [2019 - 2019] Confluent Inc.
#

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "5.0.x"
