name: common
lang: unknown
lang_version: unknown
codeowners:
  enable: true
semaphore:
  enable: true
  run_pint_merge: true
  pipeline_type: cp
  nano_version: true
  pr_ci_gating:
    enable: true
    project_name: common
  status_level: block
  extra_deploy_args: "-Pjenkins"
  extra_build_args: "-Pjenkins"
  downstream_projects: ["rest-utils", "ksql", "newwave", "kafka-connect-replicator", "hub-client"]
git:
  enable: true
code_artifact:
  enable: true
  package_paths:
    - maven-snapshots/maven/io.confluent/disk-usage-agent
    - maven-snapshots/maven/io.confluent/common
    - maven-snapshots/maven/io.confluent/common-*
    - maven-snapshots/maven/io.confluent/confluent-log4j2-extensions
    - maven-snapshots/maven/io.confluent/confluent-log4j-extensions
    - maven-snapshots/maven/io.confluent/build-tools
    - maven-snapshots/maven/io.confluent/assembly-plugin-boilerplate
